### ISSUE TITLE
Can this break valid rust code?

### ISSUE THREAD

**Issue by tausifcreates** [jeremyBanks/you-can#2]
Can this crate break/fail to compile valid rust code?
Otherwise, this tool is awesome!

Thanks.

**Comment by jeremyBanks** [comment]
:wave: I'm pretty sure that it shouldn't break valid code, unless that code has declarations such as `#[forbid(unsafe)]`, or there's another weird macro being applied to the same code which doesn't like the syntax modifications this one makes. My understanding is that using "unbounded" lifetimes like this should always cause the compiler to ignore them, so it shouldn't be possible to introduce an error/conflict as a result.

However, I haven't tested it super-extensively, so it's plausible there are some situations with complex lifetime relationships that are outside of my understanding where something could go wrong. I'd be a little surprised, but not shocked.

Cheers

**Comment by tausifcreates** [comment]
Thanks for the response! :)
